"""
Django settings for my_mtproto_backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

VPN_PAYMENT_WRITER_LOCK_PATH = os.environ.get(
    "VPN_PAYMENT_WRITER_LOCK_PATH",
    str(BASE_DIR / "data" / "vpn-payment-writer.lock"),
)
VPN_PAYMENT_WORKER_OWNER_LOCK_PATH = os.environ.get(
    "VPN_PAYMENT_WORKER_OWNER_LOCK_PATH",
    str(BASE_DIR / "data" / "vpn-payment-worker.owner.lock"),
)
VPN_PAYMENT_WORKER_OWNER_PID_PATH = os.environ.get(
    "VPN_PAYMENT_WORKER_OWNER_PID_PATH",
    str(BASE_DIR / "data" / "vpn-payment-worker.owner.pid"),
)
VPN_SUBSCRIPTION_BASE_URL = os.environ.get(
    "VPN_SUBSCRIPTION_BASE_URL",
    "https://mtprotokeys.ru/api/v1/vpn/subscriptions",
)

load_dotenv(BASE_DIR.parent / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "1"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "beatvault.ru",
    "www.beatvault.ru",
    "django",
    "79.174.81.80",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.users",
    "apps.vds",
    "apps.music",
    "apps.payments",
    "apps.vpn",
    "apps.notifications",
    "rest_framework",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "config.middlewares.RequestLoggingMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # ← вот эта строчка
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "data", "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = "static/"

AUTH_USER_MODEL = "users.SystemUser"

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# VLESS sales fail closed until an operator explicitly enables them.
VPN_SALES_ENABLED = os.getenv("VPN_SALES_ENABLED") == "1"
VPN_AGENT_CONTRACT_VERSION = os.getenv("VPN_AGENT_CONTRACT_VERSION", "v1")
VPN_AGENT_SNAPSHOT_SCHEMA_VERSION = os.getenv(
    "VPN_AGENT_SNAPSHOT_SCHEMA_VERSION", "1.0"
)
VPN_AGENT_EXPECTED_SHA = os.getenv(
    "VPN_AGENT_EXPECTED_SHA", "20ae654fc460163fe80aa82051ea9bb22f6d664a"
)
VPN_AGENT_EXPECTED_XRAY_VERSION = os.getenv(
    "VPN_AGENT_EXPECTED_XRAY_VERSION", "26.7.11"
)
VPN_AGENT_EXPECTED_XRAY_IMAGE_DIGEST = os.getenv(
    "VPN_AGENT_EXPECTED_XRAY_IMAGE_DIGEST",
    "sha256:a1644183accdb0b5be967093fe34be756fd5de15fe2ee0206e842ae17350967f",
)
VPN_AGENT_MAX_RESPONSE_BYTES = int(os.getenv("VPN_AGENT_MAX_RESPONSE_BYTES", "65536"))
VPN_AGENT_CONNECT_TIMEOUT_SECONDS = float(
    os.getenv("VPN_AGENT_CONNECT_TIMEOUT_SECONDS", "2.0")
)
VPN_AGENT_READ_TIMEOUT_SECONDS = float(
    os.getenv("VPN_AGENT_READ_TIMEOUT_SECONDS", "10.0")
)
VPN_PAYMENT_INTENT_TTL_SECONDS = int(os.getenv("VPN_PAYMENT_INTENT_TTL_SECONDS", "900"))
