# Generated by Django 6.0.2 on 2026-06-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_stars_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stars_price',
            field=models.PositiveIntegerField(default=80, verbose_name='цена в звёздах'),
        ),
    ]
