# Generated by Django 6.0.2 on 2026-07-16 01:24

import apps.payments.models
import django.db.models.deletion
from django.conf import settings
from django.core.validators import MinValueValidator, RegexValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_vless_payment_expand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='дата обновления')),
                ('invoice_payload', models.CharField(default=apps.payments.models.generate_invoice_payload, max_length=64, unique=True, validators=[RegexValidator(message='Payload должен быть 64-символьным lowercase hex token.', regex='\\A[0-9a-f]{64}\\Z')], verbose_name='invoice payload')),
                ('currency', models.CharField(max_length=8, verbose_name='валюта')),
                ('amount', models.PositiveBigIntegerField(validators=[MinValueValidator(1)], verbose_name='сумма в минимальных единицах валюты')),
                ('provider', models.CharField(choices=[('yukassa', 'ЮKassa'), ('stars', 'Telegram Stars')], max_length=16, verbose_name='провайдер')),
                ('expires_at', models.DateTimeField(verbose_name='действует до')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('precheckout_approved', 'Pre-checkout одобрен'), ('paid', 'Оплачен'), ('expired', 'Истёк'), ('cancelled', 'Отменён')], default='created', max_length=32, verbose_name='статус')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='payments.product', verbose_name='товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'намерение платежа',
                'verbose_name_plural': 'намерения платежей',
                'constraints': [models.CheckConstraint(condition=models.Q(('invoice_payload__regex', '\\A[0-9a-f]{64}\\Z')), name='valid_payment_intent_payload')],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='дата обновления')),
                ('provider', models.CharField(choices=[('yukassa', 'ЮKassa'), ('stars', 'Telegram Stars')], max_length=16, verbose_name='провайдер')),
                ('charge_id', models.CharField(verbose_name='ID платежа у провайдера')),
                ('currency', models.CharField(max_length=8, verbose_name='валюта')),
                ('amount', models.PositiveBigIntegerField(validators=[MinValueValidator(1)], verbose_name='сумма в минимальных единицах валюты')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='принят')),
                ('status', models.CharField(choices=[('received', 'Получен'), ('processing', 'Обрабатывается'), ('retry', 'Ожидает повтора'), ('applied', 'Применён')], default='received', max_length=16, verbose_name='статус')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='число попыток')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='следующая попытка')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='начало обработки')),
                ('lease_id', models.UUIDField(blank=True, null=True, verbose_name='ID аренды')),
                ('last_error_code', models.CharField(blank=True, max_length=64, verbose_name='безопасный код последней ошибки')),
                ('intent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='payments.paymentintent', verbose_name='намерение платежа')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='payments.payment', verbose_name='применённый платёж')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='payments.product', verbose_name='товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'квитанция платежа',
                'verbose_name_plural': 'квитанции платежей',
                'constraints': [
                    models.UniqueConstraint(fields=('provider', 'charge_id'), name='uniq_payment_receipt_identity'),
                    models.CheckConstraint(condition=models.Q(('charge_id', ''), _negated=True), name='non_empty_payment_receipt_charge_id'),
                    models.CheckConstraint(condition=models.Q(models.Q(('lease_id__isnull', False), ('processing_started_at__isnull', False), ('status', 'processing')), models.Q(models.Q(('status', 'processing'), _negated=True), ('lease_id__isnull', True), ('processing_started_at__isnull', True)), _connector='OR'), name='coherent_payment_receipt_lease'),
                    models.CheckConstraint(condition=models.Q(models.Q(('next_attempt_at__isnull', False), ('status', 'retry')), models.Q(models.Q(('status', 'retry'), _negated=True), ('next_attempt_at__isnull', True)), _connector='OR'), name='coherent_payment_receipt_retry'),
                    models.CheckConstraint(condition=models.Q(models.Q(('payment__isnull', False), ('status', 'applied')), models.Q(models.Q(('status', 'applied'), _negated=True), ('payment__isnull', True)), _connector='OR'), name='coherent_payment_receipt_applied'),
                ],
            },
        ),
    ]
