# Generated by Django 6.0.2 on 2026-07-16 06:09

from django.db import migrations, models


def backfill_applied_at(apps, schema_editor):
    PaymentReceipt = apps.get_model("payments", "PaymentReceipt")
    PaymentReceipt.objects.filter(status="applied", applied_at__isnull=True).update(
        applied_at=models.F("updated_at")
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0007_paymentintent_paymentreceipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentreceipt",
            name="applied_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="применён"),
        ),
        migrations.RunPython(backfill_applied_at, noop_reverse),
    ]
