# Generated by Django 6.0.2 on 2026-08-09 10:32

import apps.payments.enums
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_method_commission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptopaymentintent',
            options={'verbose_name': 'Платёж Crypto Pay', 'verbose_name_plural': 'Платежи Crypto Pay'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Способ оплаты', 'verbose_name_plural': 'Способы оплаты'},
        ),
        migrations.AlterModelOptions(
            name='plategapaymentintent',
            options={'verbose_name': 'Платёж Platega', 'verbose_name_plural': 'Платежи Platega'},
        ),
        migrations.AlterField(
            model_name='cryptopaymentintent',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='результат выдан'),
        ),
        migrations.AlterField(
            model_name='cryptopaymentintent',
            name='fulfillment_attempted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='попытка выдачи результата'),
        ),
        migrations.AlterField(
            model_name='cryptopaymentintent',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crypto_payment_intents', to=settings.AUTH_USER_MODEL, verbose_name='инициатор'),
        ),
        migrations.AlterField(
            model_name='cryptopaymentintent',
            name='last_error_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='код последней ошибки'),
        ),
        migrations.AlterField(
            model_name='cryptopaymentintent',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='уведомление отправлено'),
        ),
        migrations.AlterField(
            model_name='cryptopaymentintent',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='оплачен'),
        ),
        migrations.AlterField(
            model_name='cryptopaymentintent',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crypto_intent', to='payments.payment', verbose_name='платёж'),
        ),
        migrations.AlterField(
            model_name='cryptopaymentintent',
            name='product_code',
            field=models.CharField(max_length=32, verbose_name='код продукта'),
        ),
        migrations.AlterField(
            model_name='cryptopaymentintent',
            name='provider_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='создан у провайдера'),
        ),
        migrations.AlterField(
            model_name='cryptopaymentintent',
            name='provider_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='истекает у провайдера'),
        ),
        migrations.AlterField(
            model_name='cryptopaymentintent',
            name='provider_invoice_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='ID счёта Crypto Pay'),
        ),
        migrations.AlterField(
            model_name='cryptopaymentintent',
            name='provider_invoice_url',
            field=models.URLField(blank=True, max_length=512, verbose_name='URL счёта Crypto Pay'),
        ),
        migrations.AlterField(
            model_name='cryptopaymentintent',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный UUID'),
        ),
        migrations.AlterField(
            model_name='cryptopaymentintent',
            name='purchase_kind',
            field=models.CharField(choices=[(apps.payments.enums.PaymentKindEnum['SUBSCRIPTION'], 'Подписка'), (apps.payments.enums.PaymentKindEnum['VPN_SUBSCRIPTION'], 'VPN-подписка'), (apps.payments.enums.PaymentKindEnum['GIFT_CERTIFICATE'], 'Подарочный сертификат')], max_length=32, verbose_name='тип покупки'),
        ),
        migrations.AlterField(
            model_name='cryptopaymentintent',
            name='rub_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма в рублях'),
        ),
        migrations.AlterField(
            model_name='cryptopaymentintent',
            name='status',
            field=models.CharField(choices=[(apps.payments.enums.CryptoPaymentIntentStatusEnum['CREATING'], 'creating'), (apps.payments.enums.CryptoPaymentIntentStatusEnum['ACTIVE'], 'active'), (apps.payments.enums.CryptoPaymentIntentStatusEnum['LOCAL_EXPIRED'], 'local_expired'), (apps.payments.enums.CryptoPaymentIntentStatusEnum['PROCESSING'], 'processing'), (apps.payments.enums.CryptoPaymentIntentStatusEnum['RETRYABLE'], 'retryable'), (apps.payments.enums.CryptoPaymentIntentStatusEnum['FULFILLED'], 'fulfilled'), (apps.payments.enums.CryptoPaymentIntentStatusEnum['CREATE_FAILED'], 'create_failed'), (apps.payments.enums.CryptoPaymentIntentStatusEnum['PROVIDER_EXPIRED'], 'provider_expired')], default=apps.payments.enums.CryptoPaymentIntentStatusEnum['CREATING'], max_length=32, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='plategapaymentintent',
            name='currency',
            field=models.CharField(default='RUB', max_length=3, verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='plategapaymentintent',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='результат выдан'),
        ),
        migrations.AlterField(
            model_name='plategapaymentintent',
            name='fulfillment_attempted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='попытка выдачи результата'),
        ),
        migrations.AlterField(
            model_name='plategapaymentintent',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platega_payment_intents', to=settings.AUTH_USER_MODEL, verbose_name='инициатор'),
        ),
        migrations.AlterField(
            model_name='plategapaymentintent',
            name='last_error_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='код последней ошибки'),
        ),
        migrations.AlterField(
            model_name='plategapaymentintent',
            name='notification_queued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='уведомление поставлено в очередь'),
        ),
        migrations.AlterField(
            model_name='plategapaymentintent',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='уведомление отправлено'),
        ),
        migrations.AlterField(
            model_name='plategapaymentintent',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platega_intent', to='payments.payment', verbose_name='платёж'),
        ),
        migrations.AlterField(
            model_name='plategapaymentintent',
            name='payment_method',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='plategapaymentintent',
            name='product_code',
            field=models.CharField(max_length=32, verbose_name='код продукта'),
        ),
        migrations.AlterField(
            model_name='plategapaymentintent',
            name='provider_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='истекает у провайдера'),
        ),
        migrations.AlterField(
            model_name='plategapaymentintent',
            name='provider_payment_url',
            field=models.URLField(blank=True, max_length=512, verbose_name='URL оплаты Platega'),
        ),
        migrations.AlterField(
            model_name='plategapaymentintent',
            name='provider_transaction_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='ID транзакции Platega'),
        ),
        migrations.AlterField(
            model_name='plategapaymentintent',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный UUID'),
        ),
        migrations.AlterField(
            model_name='plategapaymentintent',
            name='purchase_kind',
            field=models.CharField(choices=[(apps.payments.enums.PaymentKindEnum['SUBSCRIPTION'], 'Подписка'), (apps.payments.enums.PaymentKindEnum['VPN_SUBSCRIPTION'], 'VPN-подписка'), (apps.payments.enums.PaymentKindEnum['GIFT_CERTIFICATE'], 'Подарочный сертификат')], max_length=32, verbose_name='тип покупки'),
        ),
        migrations.AlterField(
            model_name='plategapaymentintent',
            name='rub_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма в рублях'),
        ),
        migrations.AlterField(
            model_name='plategapaymentintent',
            name='status',
            field=models.CharField(choices=[(apps.payments.enums.PlategaPaymentIntentStatusEnum['CREATING'], 'creating'), (apps.payments.enums.PlategaPaymentIntentStatusEnum['ACTIVE'], 'active'), (apps.payments.enums.PlategaPaymentIntentStatusEnum['LOCAL_EXPIRED'], 'local_expired'), (apps.payments.enums.PlategaPaymentIntentStatusEnum['PROCESSING'], 'processing'), (apps.payments.enums.PlategaPaymentIntentStatusEnum['RETRYABLE'], 'retryable'), (apps.payments.enums.PlategaPaymentIntentStatusEnum['PROVIDER_CANCELED'], 'provider_canceled'), (apps.payments.enums.PlategaPaymentIntentStatusEnum['CREATE_FAILED'], 'create_failed'), (apps.payments.enums.PlategaPaymentIntentStatusEnum['FULFILLED'], 'fulfilled')], default=apps.payments.enums.PlategaPaymentIntentStatusEnum['CREATING'], max_length=32, verbose_name='статус'),
        ),
    ]
