# Generated by Django 6.0.2 on 2026-06-06 14:50

import apps.notifications.enums
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='дата обновления')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст сообщения (HTML, поддерживает {переменные})')),
                ('button_text', models.CharField(blank=True, default='', max_length=128, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(blank=True, default='', max_length=512, verbose_name='URL кнопки (поддерживает {переменные})')),
            ],
            options={
                'verbose_name': 'Шаблон уведомления',
                'verbose_name_plural': 'Шаблоны уведомлений',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='дата обновления')),
                ('filter_type', models.IntegerField(choices=[(apps.notifications.enums.FilterType['ALL_ACTIVE'], 'Все активные пользователи'), (apps.notifications.enums.FilterType['EXPIRING_SOON'], 'Ключ истекает скоро'), (apps.notifications.enums.FilterType['NOT_SUBSCRIBED'], 'Не подписаны на канал')], verbose_name='Фильтр получателей')),
                ('filter_params', models.JSONField(blank=True, default=dict, verbose_name='Параметры фильтра')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Статический контекст для шаблона')),
                ('context_resolver', models.IntegerField(choices=[(apps.notifications.enums.ContextResolverType['NONE'], 'Без персонального контекста'), (1, 'Ссылка на активный ключ')], default=apps.notifications.enums.ContextResolverType['NONE'], verbose_name='Персональный контекст')),
                ('status', models.IntegerField(choices=[(apps.notifications.enums.MailingStatus['DRAFT'], 'Черновик'), (apps.notifications.enums.MailingStatus['SENDING'], 'Отправляется'), (apps.notifications.enums.MailingStatus['COMPLETED'], 'Завершена'), (apps.notifications.enums.MailingStatus['FAILED'], 'Ошибка')], default=apps.notifications.enums.MailingStatus['DRAFT'], verbose_name='Статус')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлена')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
