# Generated by Django 6.0.2 on 2026-06-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_seed_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='include_payment_buttons',
            field=models.BooleanField(default=False, verbose_name='Прикрепить кнопки оплаты'),
        ),
    ]
