# Generated by Django 6.0.2 on 2026-06-06 20:15

import apps.notifications.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationtemplate_include_payment_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='failed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ошибок'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='sent_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.IntegerField(choices=[(apps.notifications.enums.MailingStatus['DRAFT'], 'Черновик'), (apps.notifications.enums.MailingStatus['SENDING'], 'Отправляется'), (apps.notifications.enums.MailingStatus['COMPLETED'], 'Завершена'), (apps.notifications.enums.MailingStatus['FAILED'], 'Ошибка'), (apps.notifications.enums.MailingStatus['PARTIALLY_COMPLETED'], 'Частично завершена')], default=apps.notifications.enums.MailingStatus['DRAFT'], verbose_name='Статус'),
        ),
    ]
