# Generated by Django 6.0.2 on 2026-06-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_set_payment_buttons_on_expiry_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='button_callback_data',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='callback_data кнопки'),
        ),
    ]
