# Generated by Django 6.0.2 on 2026-06-11

from django.db import migrations


def forwards(apps, schema_editor):
    NotificationTemplate = apps.get_model("notifications", "NotificationTemplate")
    template = NotificationTemplate.objects.get(slug="proxy_purchased")

    # Update text to use {expired_date} instead of hardcoded "30 дней"
    template.text = (
        "🎉 <b>Спасибо за покупку!</b>\n\n"
        "✨ Ваш VPN-ключ готов к использованию.\n"
        "👉 Нажмите кнопку <b>«🇳🇱 Мои серверы»</b> ниже.\n\n"
        "⏳ <b>Важно:</b> ссылка действует до <b>{expired_date}</b>.\n"
        "🗓 После этого срока доступ потребуется продлить."
    )

    # Remove link from button_url and add callback_data
    template.button_text = "🇳🇱 Мои серверы"
    template.button_url = ""
    template.button_callback_data = "my_servers"

    template.save()


def backwards(apps, schema_editor):
    NotificationTemplate = apps.get_model("notifications", "NotificationTemplate")
    template = NotificationTemplate.objects.get(slug="proxy_purchased")

    # Restore original template
    template.text = (
        "🎉 <b>Спасибо за покупку!</b>\n\n"
        "✨ Ваш VPN-ключ готов к использованию.\n"
        "👉 Нажмите кнопку <b>«🇳🇱 Подключиться»</b> ниже.\n\n"
        "⏳ <b>Важно:</b> ссылка действует <b>30 дней</b> с момента покупки.\n"
        "🗓 После этого срока доступ потребуется продлить."
    )
    template.button_text = "🇳🇱 Подключиться"
    template.button_url = "{link}"
    template.button_callback_data = ""

    template.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notificationtemplate_button_callback_data'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
