# Generated by Django 6.0.2 on 2026-06-14 17:52

import apps.notifications.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_update_proxy_purchased_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='context_resolver',
            field=models.IntegerField(choices=[(apps.notifications.enums.ContextResolverType['NONE'], 'Без персонального контекста')], default=apps.notifications.enums.ContextResolverType['NONE'], verbose_name='Персональный контекст'),
        ),
    ]
