# Generated by Django 6.0.2 on 2026-03-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_systemuser_notified_update_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='new_link_sent',
            field=models.BooleanField(default=False, verbose_name='отправлена новая ссылка вида space.beatvault.ru'),
        ),
    ]
