# Generated by Django 6.0.2 on 2026-04-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_systemuser_new_link_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='is_agree',
            field=models.BooleanField(default=False, verbose_name='согласен с публикацией в канале'),
        ),
    ]
