services:
  django:
    build: .
    container_name: django
    entrypoint: ["./entrypoint.sh"]
    volumes:
      - static_volume:/app/static
      - ./data:/app/data
    env_file:
      - .env
    expose:
      - 8000
    networks:
      - backend

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/static:ro
      - ./certbot/conf:/etc/nginx/ssl:ro
      - ./certbot/www:/var/www/certbot:ro
    expose:
      - "8443"
      - "80"
    networks:
      - backend
    depends_on:
      - django
      - flower

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - backend

  celery-worker:
    container_name: celery-worker
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - backend

  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -A config beat --loglevel=info
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
      - celery-worker
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - backend

  flower:
    build: .
    container_name: flower
    command: celery -A config flower --port=5555 --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}
    expose:
      - 5555
    depends_on:
      - redis
      - celery-worker
      - celery-beat
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    networks:
      - backend

  bot:
    build:
      context: bot
      dockerfile: Dockerfile
    container_name: telegram-bot
    env_file:
      - ./bot/.env
    restart: unless-stopped
    networks:
      - backend


volumes:
  static_volume:

networks:
  backend:
    driver: bridge