# Generated by Django 6.0.2 on 2026-08-29 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FortuneSpin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активность"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="дата обновления"
                    ),
                ),
                (
                    "prize_apples",
                    models.PositiveIntegerField(verbose_name="выиграно яблок"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fortune_spins",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "вращение колеса",
                "verbose_name_plural": "вращения колеса",
                "ordering": ("-created_at", "-pk"),
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="fortune_user_created_idx"
                    )
                ],
            },
        ),
    ]
