# Generated by Django 6.0.2 on 2026-02-28 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vds', '0003_mtprotokey_was_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtprotokey',
            name='payment',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='_payment_legacy',
                to=settings.AUTH_USER_MODEL,
                verbose_name='оплата на Tribute',
            ),
        ),
    ]
