# Generated by Django 6.0.2 on 2026-03-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0009_mtprotokey_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdsinstance',
            name='user_limit',
            field=models.PositiveSmallIntegerField(default=200, verbose_name='лимит пользователей'),
        ),
    ]
