# Generated by Django 6.0.2 on 2026-04-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0010_vdsinstance_user_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtprotokey',
            name='is_winner',
            field=models.BooleanField(default=False, verbose_name='победитель конкурса'),
        ),
    ]
