# Generated by Django 6.0.2 on 2026-06-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0013_remove_mtprotokey_is_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdsinstance',
            name='is_keys_available',
            field=models.BooleanField(default=True, verbose_name='выпуск ключей доступен'),
        ),
    ]
