# Generated by Django 6.0.2 on 2026-06-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0014_vdsinstance_is_keys_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdsinstance',
            name='name',
            field=models.CharField(verbose_name='название сервера'),
        ),
    ]
