# Generated by Django 6.0.2 on 2026-06-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0015_alter_vdsinstance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdsinstance',
            name='location',
            field=models.CharField(blank=True, default='', verbose_name='геолокация'),
        ),
    ]
