# Generated by Django 6.0.2 on 2026-06-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0016_vdsinstance_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdsinstance',
            name='is_healthy',
            field=models.BooleanField(default=True, verbose_name='сервер здоров'),
        ),
    ]
