# Generated by Django 6.0.2 on 2026-06-14 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0017_vdsinstance_is_healthy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtprotokey',
            name='vds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='vds.vdsinstance', verbose_name='VDS сервер'),
        ),
    ]
