# Generated by Django 6.0.2 on 2026-06-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0018_alter_mtprotokey_vds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtprotokey',
            name='node_number',
        ),
        migrations.RemoveField(
            model_name='mtprotokey',
            name='tls_domain',
        ),
        migrations.RemoveField(
            model_name='mtprotokey',
            name='vds',
        ),
        migrations.RemoveField(
            model_name='vdsinstance',
            name='user_limit',
        ),
    ]
