# Generated by Django 6.0.2 on 2026-06-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0019_remove_mtprotokey_node_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vdsinstance',
            options={'ordering': ['number'], 'verbose_name': 'VDS сервер', 'verbose_name_plural': 'VDS серверы'},
        ),
    ]
