# Generated by Django 6.0.2 on 2026-07-04 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0020_alter_vdsinstance_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='дата обновления')),
                ('name', models.CharField(verbose_name='название хостинга')),
                ('link', models.URLField(verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'Хостинг',
                'verbose_name_plural': 'Хостинги',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vdsinstance',
            name='expired_at',
            field=models.DateField(blank=True, null=True, verbose_name='оплачен до'),
        ),
        migrations.AddField(
            model_name='vdsinstance',
            name='hosting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vds_instances', to='vds.hosting', verbose_name='хостинг'),
        ),
    ]
