from __future__ import annotations

# Generated by Django 6.0.2 on 2026-08-15 12:49

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vds", "0021_hosting_vdsinstance_expired_at_vdsinstance_hosting"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активность"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="дата обновления",
                    ),
                ),
                (
                    "ipv4",
                    models.GenericIPAddressField(
                        protocol="IPv4",
                        unique=True,
                        verbose_name="IPv4-адрес",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.01")
                            )
                        ],
                        verbose_name="стоимость в месяц",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USDT", "USDT"),
                            ("RUB", "RUB"),
                            ("EUR", "EUR"),
                            ("USD", "USD"),
                        ],
                        max_length=4,
                        verbose_name="валюта",
                    ),
                ),
                (
                    "next_payment_date",
                    models.DateField(verbose_name="дата следующего платежа"),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="назначение"),
                ),
                (
                    "hosting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_servers",
                        to="vds.hosting",
                        verbose_name="хостинг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проектный сервер",
                "verbose_name_plural": "Проектные серверы",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price__gt", Decimal("0.00"))),
                        name="project_server_price_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("currency__in", ["USDT", "RUB", "EUR", "USD"])
                        ),
                        name="project_server_currency_valid",
                    ),
                ],
            },
        ),
    ]
