from __future__ import annotations

# Generated by Django 6.0.2 on 2026-07-31

import apps.vpn.models
import django.db.models.deletion
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0010_normalize_none_telegram_usernames"),
    ]

    operations = [
        migrations.CreateModel(
            name="VPNInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="активность")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True, verbose_name="дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="дата обновления")),
                ("number", models.PositiveSmallIntegerField(verbose_name="порядковый номер")),
                ("name", models.CharField(verbose_name="название")),
                ("location", models.CharField(blank=True, default="", verbose_name="локация")),
                ("management_url", models.URLField(verbose_name="URL управления")),
                ("public_host", models.CharField(verbose_name="публичный хост")),
                ("vless_port", models.PositiveIntegerField(verbose_name="VLESS порт")),
                ("reality_sni", models.CharField(verbose_name="REALITY SNI")),
                ("reality_public_key", models.CharField(verbose_name="REALITY публичный ключ")),
                ("reality_short_id", models.CharField(verbose_name="REALITY short ID")),
                ("hysteria_port", models.PositiveIntegerField(verbose_name="Hysteria порт")),
                ("hysteria_sni", models.CharField(verbose_name="Hysteria SNI")),
                ("hysteria_obfs", models.CharField(verbose_name="Hysteria obfuscation")),
            ],
            options={
                "verbose_name": "VPN-нода",
                "verbose_name_plural": "VPN-ноды",
                "ordering": ["number", "pk"],
            },
        ),
        migrations.CreateModel(
            name="VPNSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="активность")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True, verbose_name="дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="дата обновления")),
                ("token", models.CharField(default=apps.vpn.models._generate_subscription_token, max_length=64, unique=True, verbose_name="токен подписки")),
                ("vless_uuid", models.UUIDField(default=uuid.uuid4, unique=True, verbose_name="VLESS UUID")),
                ("hysteria_secret", models.CharField(default=apps.vpn.models._generate_hysteria_secret, max_length=64, unique=True, verbose_name="Hysteria credential")),
                ("expired_at", models.DateTimeField(verbose_name="истекает")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="vpn_subscription", to="users.systemuser", verbose_name="пользователь")),
            ],
            options={
                "verbose_name": "VPN-подписка",
                "verbose_name_plural": "VPN-подписки",
            },
        ),
    ]
