# Generated by Django 6.0.2 on 2026-07-16 01:50

import apps.vpn.enums
import apps.vpn.models
import apps.vpn.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0006_vless_payment_expand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='дата обновления')),
                ('subscription_token', models.CharField(default=apps.vpn.models.generate_subscription_token, editable=False, max_length=128, unique=True, validators=[django.core.validators.MinLengthValidator(43)], verbose_name='subscription token')),
                ('desired_uuid', models.UUIDField(default=uuid.uuid4, verbose_name='желаемый UUID')),
                ('desired_revision', models.PositiveBigIntegerField(default=1, verbose_name='желаемая revision')),
                ('published_uuid', models.UUIDField(blank=True, null=True, verbose_name='опубликованный UUID')),
                ('published_revision', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='опубликованная revision')),
                ('expired_at', models.DateTimeField(verbose_name='действует до')),
                ('state', models.CharField(choices=[('preparing', 'Подготавливается'), ('ready', 'Готов'), ('expired', 'Истёк'), ('disabled_refund', 'Отключён после возврата')], default=apps.vpn.enums.VPNAccessState['PREPARING'], max_length=32, verbose_name='состояние')),
                ('state_revision', models.PositiveBigIntegerField(default=1, verbose_name='revision состояния')),
                ('ready_notification_revision', models.PositiveBigIntegerField(default=0, verbose_name='последняя уведомлённая revision')),
                ('disabled_at', models.DateTimeField(blank=True, null=True, verbose_name='отключён')),
                ('disabled_reason', models.CharField(blank=True, max_length=128, verbose_name='причина отключения')),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_accesses_disabled', to=settings.AUTH_USER_MODEL, verbose_name='отключил')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_access', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'VPN-доступ',
                'verbose_name_plural': 'VPN-доступы',
            },
        ),
        migrations.CreateModel(
            name='VPNNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='дата обновления')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='имя')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='порядковый номер')),
                ('location', models.CharField(max_length=128, verbose_name='локация')),
                ('host', models.CharField(max_length=255, validators=[apps.vpn.validators.validate_public_host], verbose_name='публичный host')),
                ('port', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='публичный порт')),
                ('agent_base_url', models.URLField(max_length=255, validators=[apps.vpn.validators.validate_https_base_url], verbose_name='HTTPS URL агента')),
                ('agent_secret_key', models.CharField(max_length=128, validators=[apps.vpn.validators.validate_agent_secret_lookup_key], verbose_name='lookup key секрета')),
                ('agent_contract_version', models.CharField(max_length=16, verbose_name='версия контракта агента')),
                ('health_state', models.CharField(choices=[('new', 'Новая'), ('syncing', 'Синхронизируется'), ('ready', 'Готов'), ('unhealthy', 'Нездорова'), ('incompatible', 'Несовместима'), ('over_capacity', 'Переполнена')], default=apps.vpn.enums.VPNNodeHealthState['NEW'], max_length=32, verbose_name='health state')),
                ('is_access_available', models.BooleanField(default=True, verbose_name='доступна для выдачи')),
                ('desired_snapshot_revision', models.PositiveBigIntegerField(default=0, verbose_name='желаемая snapshot revision')),
                ('desired_snapshot_hash', models.CharField(blank=True, max_length=64, validators=[apps.vpn.validators.validate_optional_sha256], verbose_name='желаемый snapshot hash')),
                ('applied_snapshot_revision', models.PositiveBigIntegerField(default=0, verbose_name='применённая snapshot revision')),
                ('applied_snapshot_hash', models.CharField(blank=True, max_length=64, validators=[apps.vpn.validators.validate_optional_sha256], verbose_name='применённый snapshot hash')),
                ('last_health_at', models.DateTimeField(blank=True, null=True, verbose_name='последний health check')),
                ('last_error_code', models.CharField(blank=True, max_length=64, verbose_name='последний код ошибки')),
                ('reality_public_key', models.CharField(max_length=64, validators=[apps.vpn.validators.validate_x25519_public_key], verbose_name='REALITY public key')),
                ('reality_short_id', models.CharField(max_length=16, validators=[apps.vpn.validators.validate_reality_short_id], verbose_name='REALITY short ID')),
                ('reality_server_name', models.CharField(max_length=253, validators=[apps.vpn.validators.validate_sni], verbose_name='REALITY SNI')),
                ('reality_fingerprint', models.CharField(choices=[('chrome', 'Chrome')], default=apps.vpn.enums.VPNRealityFingerprint['CHROME'], max_length=16, verbose_name='REALITY fingerprint')),
                ('reality_flow', models.CharField(choices=[('xtls-rprx-vision', 'XTLS Vision')], default=apps.vpn.enums.VPNRealityFlow['XTLS_RPRX_VISION'], max_length=32, verbose_name='VLESS flow')),
            ],
            options={
                'verbose_name': 'VPN-нода',
                'verbose_name_plural': 'VPN-ноды',
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('host', 'port'), name='uniq_vpn_node_public_authority'), models.CheckConstraint(condition=models.Q(('applied_snapshot_revision__lte', models.F('desired_snapshot_revision'))), name='vpn_node_applied_snapshot_lte_desired'), models.CheckConstraint(condition=models.Q(models.Q(('desired_snapshot_hash', ''), ('desired_snapshot_revision', 0)), models.Q(('desired_snapshot_revision__gt', 0), models.Q(('desired_snapshot_hash', ''), _negated=True)), _connector='OR'), name='vpn_node_desired_snapshot_pair'), models.CheckConstraint(condition=models.Q(models.Q(('applied_snapshot_hash', ''), ('applied_snapshot_revision', 0)), models.Q(('applied_snapshot_revision__gt', 0), models.Q(('applied_snapshot_hash', ''), _negated=True)), _connector='OR'), name='vpn_node_applied_snapshot_pair'), models.CheckConstraint(condition=models.Q(models.Q(('health_state', apps.vpn.enums.VPNNodeHealthState['READY']), _negated=True), models.Q(('desired_snapshot_revision__gt', 0), ('applied_snapshot_hash', models.F('desired_snapshot_hash')), ('applied_snapshot_revision', models.F('desired_snapshot_revision')), models.Q(('desired_snapshot_hash', ''), _negated=True)), _connector='OR'), name='vpn_node_ready_snapshot_exact')],
            },
        ),
        migrations.CreateModel(
            name='VPNAccessNodeApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='дата обновления')),
                ('desired_revision', models.PositiveBigIntegerField(verbose_name='желаемая revision')),
                ('applied_revision', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='применённая revision')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('applied', 'Применено'), ('failed', 'Ошибка')], default=apps.vpn.enums.VPNApplyStatus['PENDING'], max_length=16, verbose_name='статус')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='последняя попытка')),
                ('last_error_code', models.CharField(blank=True, max_length=64, verbose_name='последний код ошибки')),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_applies', to='vpn.vpnaccess', verbose_name='VPN-доступ')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_applies', to='vpn.vpnnode', verbose_name='VPN-нода')),
            ],
            options={
                'verbose_name': 'применение VPN-доступа на ноде',
                'verbose_name_plural': 'применения VPN-доступов на нодах',
            },
        ),
        migrations.CreateModel(
            name='VPNPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='дата обновления')),
                ('period_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='оплаченный период, дней')),
                ('expired_at_after', models.DateTimeField(verbose_name='срок после применения платежа')),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='vpn.vpnaccess', verbose_name='VPN-доступ')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vpn_purchase', to='payments.payment', verbose_name='платёж')),
            ],
            options={
                'verbose_name': 'VPN-покупка',
                'verbose_name_plural': 'VPN-покупки',
            },
        ),
        migrations.AddConstraint(
            model_name='vpnaccess',
            constraint=models.CheckConstraint(condition=models.Q(('desired_revision__gte', 1)), name='vpn_access_desired_revision_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='vpnaccess',
            constraint=models.CheckConstraint(condition=models.Q(('state_revision__gte', 1)), name='vpn_access_state_revision_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='vpnaccess',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_revision__isnull', True), ('published_uuid__isnull', True)), models.Q(('published_revision__isnull', False), ('published_uuid__isnull', False)), _connector='OR'), name='vpn_access_published_pair'),
        ),
        migrations.AddConstraint(
            model_name='vpnaccess',
            constraint=models.CheckConstraint(condition=models.Q(('published_revision__isnull', True), ('published_revision__lte', models.F('desired_revision')), _connector='OR'), name='vpn_access_published_lte_desired'),
        ),
        migrations.AddConstraint(
            model_name='vpnaccess',
            constraint=models.CheckConstraint(condition=models.Q(('published_revision__isnull', True), ('published_revision__lt', models.F('desired_revision')), ('published_uuid', models.F('desired_uuid')), _connector='OR'), name='vpn_access_published_uuid_matches_revision'),
        ),
        migrations.AddConstraint(
            model_name='vpnaccess',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', apps.vpn.enums.VPNAccessState['READY']), _negated=True), models.Q(('published_revision', models.F('desired_revision')), ('published_uuid', models.F('desired_uuid')), ('published_uuid__isnull', False)), _connector='OR'), name='vpn_access_ready_is_current'),
        ),
        migrations.AddConstraint(
            model_name='vpnaccess',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', apps.vpn.enums.VPNAccessState['DISABLED_REFUND']), _negated=True), models.Q(('disabled_at__isnull', False), ('disabled_by__isnull', False), models.Q(('disabled_reason', ''), _negated=True)), _connector='OR'), name='vpn_access_refund_has_audit'),
        ),
        migrations.AddConstraint(
            model_name='vpnaccess',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_revision__isnull', False), ('ready_notification_revision__lte', models.F('published_revision'))), ('ready_notification_revision', 0), _connector='OR'), name='vpn_access_notification_lte_published'),
        ),
        migrations.AddConstraint(
            model_name='vpnaccessnodeapply',
            constraint=models.UniqueConstraint(fields=('access', 'node'), name='uniq_vpn_access_node_apply'),
        ),
        migrations.AddConstraint(
            model_name='vpnaccessnodeapply',
            constraint=models.CheckConstraint(condition=models.Q(('desired_revision__gte', 1)), name='vpn_apply_desired_revision_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='vpnaccessnodeapply',
            constraint=models.CheckConstraint(condition=models.Q(('applied_revision__isnull', True), ('applied_revision__lte', models.F('desired_revision')), _connector='OR'), name='vpn_apply_applied_lte_desired'),
        ),
        migrations.AddConstraint(
            model_name='vpnaccessnodeapply',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', apps.vpn.enums.VPNApplyStatus['APPLIED']), _negated=True), ('applied_revision', models.F('desired_revision')), _connector='OR'), name='vpn_apply_status_has_exact_revision'),
        ),
    ]
