# Generated by Django 6.0.2 on 2026-08-15

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vpn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vpnsubscription",
            name="last_reissued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
