# Generated by Django 6.0.2 on 2026-07-16 06:07

from django.db import migrations, models


def backfill_observability_onsets(apps, schema_editor):
    VPNNode = apps.get_model("vpn", "VPNNode")
    VPNNode.objects.exclude(last_error_code="").filter(
        last_error_started_at__isnull=True
    ).update(last_error_started_at=models.F("updated_at"))
    VPNNode.objects.filter(revision_drift_started_at__isnull=True).exclude(
        desired_snapshot_revision=models.F("applied_snapshot_revision"),
        desired_snapshot_hash=models.F("applied_snapshot_hash"),
    ).update(revision_drift_started_at=models.F("updated_at"))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("vpn", "0002_revision_evidence_expand"),
    ]

    operations = [
        migrations.AddField(
            model_name="vpnnode",
            name="last_error_started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="начало непрерывной ошибки"
            ),
        ),
        migrations.AddField(
            model_name="vpnnode",
            name="revision_drift_started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="начало непрерывного revision drift"
            ),
        ),
        migrations.RunPython(backfill_observability_onsets, noop_reverse),
    ]
