# Generated by Django 6.0.2 on 2026-07-16 06:09

from django.db import migrations, models


def backfill_first_ready_at(apps, schema_editor):
    VPNAccess = apps.get_model("vpn", "VPNAccess")
    VPNAccess.objects.filter(state="ready", first_ready_at__isnull=True).update(
        first_ready_at=models.F("updated_at")
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("vpn", "0003_observability_onsets"),
    ]

    operations = [
        migrations.AddField(
            model_name="vpnaccess",
            name="first_ready_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="впервые опубликован"
            ),
        ),
        migrations.RunPython(backfill_first_ready_at, noop_reverse),
    ]
